openapi: 3.0.0
info:
  title:
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - in: body
    name: body
    description: Data credit card yang akan ditambahkan
    required: true
    schema: 
      $ref: '#/definitions/CreditCard'
responses:
  201:
    description: Data credit card berhasil ditambahkan
    schema:
      $ref: '#/definitions/CreditCard'
definitions:
  CreditCard:
    type: object
    properties:
      customer_id:
        type: string
      limitt:
        type: float
      balance:
        type: float
      interest_rate:
        type: float
    required:
      - customer_id
      - limitt
      - balance
      - interest_rate
