openapi: 3.0.0
info:
  title: Delete Satu Data Credit Card
  version: 1.0.0
tags:
  - name: Daftar API
parameters:
  - name: card_id
    in: path
    description: Card ID yang akan dihapus
    required: true
    type: integer
responses:
  200:
    description: Data credit card berhasil dihapus
  404:
    description: Data tidak ditemukan